EXPORT DEF wMapMusic EQU $C1C0
EXPORT DEF wLZAddress EQU $C1C2
EXPORT DEF wLZBank EQU $C1C4
EXPORT DEF wInputType EQU $C1C6
EXPORT DEF wAutoInputAddress EQU $C1C7
EXPORT DEF wAutoInputBank EQU $C1C9
EXPORT DEF wAutoInputLength EQU $C1CA
EXPORT DEF wGameLogicPaused EQU $C1CC
EXPORT DEF wSpriteUpdatesEnabled EQU $C1CD
EXPORT DEF wPrinterConnectionOpen EQU $C1D3
EXPORT DEF wLinkReceivedSyncBuffer EQU $C1EA
EXPORT DEF wOtherPlayerLinkMode EQU $C1EA
EXPORT DEF wOtherPlayerLinkAction EQU $C1EB
EXPORT DEF wLinkPlayerSyncBuffer EQU $C1EF
EXPORT DEF wPlayerLinkAction EQU $C1EF
EXPORT DEF wLinkTimeoutFrames EQU $C1F4
EXPORT DEF wLinkByteTimeout EQU $C1F6
EXPORT DEF wBGPals1 EQU $C200
EXPORT DEF wOBPals1 EQU $C240
EXPORT DEF wBGPals2 EQU $C280
EXPORT DEF wOBPals2 EQU $C2C0
EXPORT DEF wTilemap EQU $C3A0
EXPORT DEF wTilemapEnd EQU $C508
EXPORT DEF wLYOverrides EQU $C700
EXPORT DEF wEnemyMonNickname EQU $CAF6
EXPORT DEF wBattleMonNickname EQU $CB01
EXPORT DEF wOTClassName EQU $CB34
EXPORT DEF wAttrmap EQU $CCE0
EXPORT DEF wRequested2bppSize EQU $CE48
EXPORT DEF wRequested2bppSource EQU $CE49
EXPORT DEF wRequested2bppDest EQU $CE4B
EXPORT DEF wRequested1bppSize EQU $CE4D
EXPORT DEF wRequested1bppSource EQU $CE4E
EXPORT DEF wRequested1bppDest EQU $CE50
EXPORT DEF wOverworldDelay EQU $CEBD
EXPORT DEF wTextDelayFrames EQU $CEBE
EXPORT DEF wVBlankOccurred EQU $CEBF
EXPORT DEF wBetaTitleSequenceOpeningType EQU $CEC0
EXPORT DEF wFarDecompressPicPointer EQU $CF24
EXPORT DEF wMenuScrollPosition EQU $CF36
EXPORT DEF wStackTop EQU $CFFF
EXPORT DEF wBGP EQU $D00A
EXPORT DEF wOBP0 EQU $D00B
EXPORT DEF wOBP1 EQU $D00C
EXPORT DEF wStringBuffer1 EQU $D036
EXPORT DEF wStringBuffer2 EQU $D04B
EXPORT DEF wStateFlags EQU $D0A4
EXPORT DEF wLinkMode EQU $D0FD
EXPORT DEF wd120 EQU $D120
EXPORT DEF wTrainerClass EQU $D1DA
EXPORT DEF wROMBankBackup EQU $D212
EXPORT DEF wTempBank EQU $D213
EXPORT DEF wTextboxFlags EQU $D257
EXPORT DEF wPlayerName EQU $D25E
EXPORT DEF wMomsName EQU $D269
EXPORT DEF wRivalName EQU $D274
EXPORT DEF wRedsName EQU $D27F
EXPORT DEF wGreensName EQU $D28A
EXPORT DEF wStartDay EQU $D297
EXPORT DEF wStartHour EQU $D298
EXPORT DEF wStartMinute EQU $D299
EXPORT DEF wStartSecond EQU $D29A
EXPORT DEF wCurDay EQU $D2A7
EXPORT DEF wTimeOfDayPal EQU $D61B
EXPORT DEF wJoypadDisable EQU $D94D
EXPORT DEF hTransferShadowOAM EQU $FF80
EXPORT DEF hAGB EQU $FFEA


SECTION "sram2", SRAM[$A000], BANK[0]
sScratch::

	ds $a188 - @

sDecompressBuffer::

	ds $b060 - @

sRTCStatusFlags::
