EXPORT DEF wNamingScreenDestinationPointer EQU $C5D0
EXPORT DEF wPlayerTrademonSpeciesName EQU $C5D1
EXPORT DEF wNamingScreenCurNameLength EQU $C5D2
EXPORT DEF wNamingScreenMaxNameLength EQU $C5D3
EXPORT DEF wNamingScreenType EQU $C5D4
EXPORT DEF wNamingScreenCursorObjectPointer EQU $C5D5
EXPORT DEF wNamingScreenLastCharacter EQU $C5D7
EXPORT DEF wNamingScreenStringEntryCoord EQU $C5D8
EXPORT DEF wPlayerTrademonSenderName EQU $C5E7
EXPORT DEF wBetaPokerSGBPals EQU $C602
EXPORT DEF wOTTrademonSpeciesName EQU $C602
EXPORT DEF wBetaPokerSGBAttr EQU $C605
EXPORT DEF wBetaPokerSGBCol EQU $C606
EXPORT DEF wBetaPokerSGBRow EQU $C607
EXPORT DEF wOTTrademonSenderName EQU $C618
EXPORT DEF wHallOfFamePokemonList EQU $C700
EXPORT DEF wHallOfFamePokemonListEnd EQU $C761
EXPORT DEF wMysteryGiftPartnerName EQU $C803
EXPORT DEF wMysteryGiftPlayerName EQU $C853
EXPORT DEF wHandshakeFrameDelay EQU $C98A
EXPORT DEF wOTClassName EQU $CB34
EXPORT DEF wCurOTMon EQU $CB49
EXPORT DEF wBattleParticipantsNotFainted EQU $CB4A
EXPORT DEF wAttackMissed EQU $CB4D
EXPORT DEF wPlayerSubStatus1 EQU $CB4E
EXPORT DEF wPlayerSubStatus2 EQU $CB4F
EXPORT DEF wPlayerSubStatus3 EQU $CB50
EXPORT DEF wPlayerSubStatus4 EQU $CB51
EXPORT DEF wPlayerSubStatus5 EQU $CB52
EXPORT DEF wEnemySubStatus1 EQU $CB53
EXPORT DEF wEnemySubStatus2 EQU $CB54
EXPORT DEF wEnemySubStatus3 EQU $CB55
EXPORT DEF wEnemySubStatus4 EQU $CB56
EXPORT DEF wEnemySubStatus5 EQU $CB57
EXPORT DEF wPlayerDisableCount EQU $CB5B
EXPORT DEF wBattleAnimParam EQU $CB6F
EXPORT DEF wCurPlayerMove EQU $CBC9
EXPORT DEF wCurEnemyMove EQU $CBCA
EXPORT DEF wPayDayMoney EQU $CBD2
EXPORT DEF wEnemyBackupDVs EQU $CBD8
EXPORT DEF wDisabledMove EQU $CBDB
EXPORT DEF wLastPlayerCounterMove EQU $CBDE
EXPORT DEF wLastEnemyCounterMove EQU $CBDF
EXPORT DEF wBattleParticipantsIncludingFainted EQU $CBE2
EXPORT DEF wEffectFailed EQU $CBF3
EXPORT DEF wLastPlayerMove EQU $CC01
EXPORT DEF wLastEnemyMove EQU $CC02
EXPORT DEF wWildMonMoves EQU $CC1B
EXPORT DEF wWildMonPP EQU $CC1F
EXPORT DEF wTempMailMessage EQU $CEC2
EXPORT DEF wTempMail EQU $CEC2
EXPORT DEF wTempMailAuthor EQU $CF03
EXPORT DEF wCurBGEvent EQU $CF11
EXPORT DEF wCurCoordEvent EQU $CF11
EXPORT DEF wSeenTrainerBank EQU $CF11
EXPORT DEF wFacingTileID EQU $CF11
EXPORT DEF wCurInput EQU $CF11
EXPORT DEF wItemBallItemID EQU $CF11
EXPORT DEF wMenuItemsList EQU $CF11
EXPORT DEF wElevatorPointerBank EQU $CF11
EXPORT DEF wElevatorData EQU $CF11
EXPORT DEF wHiddenItemEvent EQU $CF11
EXPORT DEF wMartType EQU $CF11
EXPORT DEF wSeenTrainerDistance EQU $CF12
EXPORT DEF wWalkingIntoNPC EQU $CF12
EXPORT DEF wItemBallQuantity EQU $CF12
EXPORT DEF wElevatorPointer EQU $CF12
EXPORT DEF wJumpStdScriptBuffer EQU $CF12
EXPORT DEF wMartPointerBank EQU $CF12
EXPORT DEF wSeenTrainerDirection EQU $CF13
EXPORT DEF wWalkingIntoLand EQU $CF13
EXPORT DEF wHiddenItemID EQU $CF13
EXPORT DEF wMartPointer EQU $CF13
EXPORT DEF wTempTrainer EQU $CF14
EXPORT DEF wWalkingIntoEdgeWarp EQU $CF14
EXPORT DEF wElevatorOriginFloor EQU $CF14
EXPORT DEF wMovementAnimation EQU $CF15
EXPORT DEF wElevatorDataEnd EQU $CF15
EXPORT DEF wMartJumptableIndex EQU $CF15
EXPORT DEF wWalkingDirection EQU $CF16
EXPORT DEF wBargainShopFlags EQU $CF16
EXPORT DEF wFacingDirection EQU $CF17
EXPORT DEF wWalkingX EQU $CF18
EXPORT DEF wMenuCursorPositionBackup EQU $CF18
EXPORT DEF wWalkingY EQU $CF19
EXPORT DEF wMenuScrollPositionBackup EQU $CF19
EXPORT DEF wWinTextPointer EQU $CF1A
EXPORT DEF wWalkingTileCollision EQU $CF1A
EXPORT DEF wLossTextPointer EQU $CF1C
EXPORT DEF wRunningTrainerBattleScript EQU $CF20
EXPORT DEF wTempTrainerEnd EQU $CF21
EXPORT DEF wPlayerTurningDirection EQU $CF21
EXPORT DEF wMenuItemsListEnd EQU $CF21
EXPORT DEF wBoxAlignment EQU $CF23
EXPORT DEF wFarDecompressPicPointer EQU $CF24
EXPORT DEF wBattleMenuCursorPosition EQU $CF26
EXPORT DEF wCurBattleMon EQU $CF28
EXPORT DEF wCurMoveNum EQU $CF29
EXPORT DEF wLastPocket EQU $CF2A
EXPORT DEF wPartyMenuCursor EQU $CF2B
EXPORT DEF wItemsPocketCursor EQU $CF2C
EXPORT DEF wKeyItemsPocketCursor EQU $CF2D
EXPORT DEF wBallsPocketCursor EQU $CF2E
EXPORT DEF wItemsPocketScrollPosition EQU $CF31
EXPORT DEF wKeyItemsPocketScrollPosition EQU $CF32
EXPORT DEF wBallsPocketScrollPosition EQU $CF33
EXPORT DEF wTMHMPocketScrollPosition EQU $CF34
EXPORT DEF wSwitchItem EQU $CF35
EXPORT DEF wSwitchMon EQU $CF35
EXPORT DEF wSwappingMove EQU $CF35
EXPORT DEF wMenuScrollPosition EQU $CF36
EXPORT DEF wQueuedScriptBank EQU $CF3A
EXPORT DEF wQueuedScriptAddr EQU $CF3B
EXPORT DEF wStackBottom EQU $CF3D
EXPORT DEF wStackTop EQU $CFFF
EXPORT DEF wd000 EQU $D000
EXPORT DEF wJumptableIndex EQU $D001
EXPORT DEF wTitleScreenSelectedOption EQU $D002
EXPORT DEF wPackJumptableIndex EQU $D002
EXPORT DEF wNamingScreenLetterCase EQU $D002
EXPORT DEF wMomBankDigitCursorPosition EQU $D002
EXPORT DEF wFrameCounter EQU $D002
EXPORT DEF wTitleScreenTimer EQU $D003
EXPORT DEF wUnusedSGB1eColorOffset EQU $D003
EXPORT DEF wCurPocket EQU $D003
EXPORT DEF wPackUsedItem EQU $D004
EXPORT DEF wFXAnimID EQU $D005
EXPORT DEF wBGP EQU $D00A
EXPORT DEF wOBP0 EQU $D00B
EXPORT DEF wOBP1 EQU $D00C
EXPORT DEF wBattleAfterAnim EQU $D00D
EXPORT DEF wMonOrItemNameBuffer EQU $D00F
EXPORT DEF wStringBuffer1 EQU $D036
EXPORT DEF wStringBuffer2 EQU $D04B
EXPORT DEF wStringBuffer3 EQU $D060
EXPORT DEF wStringBuffer4 EQU $D075
EXPORT DEF wOptions EQU $D254
EXPORT DEF wSaveFileExists EQU $D255
EXPORT DEF wTextboxFlags EQU $D257
EXPORT DEF wOptions2 EQU $D259
EXPORT DEF wGameData EQU $D25C
EXPORT DEF wOptionsEnd EQU $D25C
EXPORT DEF wHallOfFameCount EQU $D736
EXPORT DEF wWindowStackTop EQU $D7FF
EXPORT DEF wTempTilemap EQU $D800
EXPORT DEF hClockResetTrigger EQU $FFEE
